spring:
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://security
          predicates:
            - Path=/auth/**
        - id: request-manager
          uri: lb://manager
          predicates:
            - Path=/**
          filters:
            - AuthFilter
        - id: sender-service
          uri: lb://sender
          predicates:
            - Path=/**
          filters:
            - AuthFilter
